### ISSUE TITLE
No license for project

### ISSUE THREAD

**Issue by CarwynNelson** [sinnwerkstatt/django-cookiebanner#2]
Hi,

We at https://github.com/geekzonehq are thinking of forking this project to make some improvements that would allow it to work for our project.

Unfortunately this project does not have a license specified so we are unable to fork it, or even really legally use it without ambiguity.

Would you be able to add a license to this project so that we can continue? Our preference would be GPL as that is what our project also is, but a permissive license like MIT would also work.

We are more than happy to contribute our changes back in the form of pull requests if you desire.

Cheers!

**Comment by andreasnuesslein** [comment]
Ahoyhoy! thank you for your interest :) 

https://github.com/sinnwerkstatt/django-cookiebanner/commit/8b685c5daaa8d0631f8f72d7c420a23f77d3201e
I added the GPL v3 - I hope that works for you?

**Comment by CarwynNelson** [comment]
Fantastic, thanks for your help :)

**Comment by andreasnuesslein** [comment]
You're welcome and sure: do send PRs :)
