### ISSUE TITLE
add compatibility for Django 4+

### ISSUE THREAD

**Issue by nerdoc** [sinnwerkstatt/django-cookiebanner#5]
according to the [Django docs](https://docs.djangoproject.com/en/4.1/releases/3.0/#features-deprecated-in-3-0), force_text was deprecated in Django-3.0 and is still used in django-cookie-banner.

So this library does not work with Django >= 4.0 since `force_text` was removed then.

Could you fix that?

**Comment by nerdoc** [comment]
replacing it with str() did it for me - but this is just a workaround IMHO. I even dont know what force_text is used here:
https://github.com/sinnwerkstatt/django-cookiebanner/blob/9542716f96ab10e65ef9a8d03ea0a008d204314c/cookiebanner/templatetags/cookiebanner.py#L17

**Comment by andreasnuesslein** [comment]
Hey @nerdoc , thanks for letting us know. I will look into it asap.

**Comment by andreasnuesslein** [comment]
@nerdoc could you check if it's working correctly now? cheers

**Comment by nerdoc** [comment]
Yes, works correctly! Thanks!
