### ISSUE TITLE
Show Cookie details works only on first attempt to page

### ISSUE THREAD

**Issue by bvj** [sinnwerkstatt/django-cookiebanner#6]
When save cookie preferences or reload page click on link "Show Cookie details" does nothing.

**Comment by avinczenagy** [comment]
Same issue. After the initial popup, if i accept the settings the modal disappears. When I open it again with the provided button it shows up but all the eventlisteners doesn't seem to work anymore. "Show cookie details" are not opening and saving won't save the changes made (switches).
